<form>
    <table>
        <tr>
            <td>Name</td>
            <td><input></td>
        </tr>
        <tr>
            <td>birthday</td>
            <td><input></td>
        </tr>
        <tr>
            <td>Memo</td>
            <td><textarea></textarea></td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit" value="add" /></td>
        </tr>
    </table>
</form>